---
- hosts: baseinstall
  become: true
  tasks:
    - include: deploy/packages.yml
    - include: deploy/users.yml
    - include: deploy/config.yml
    - include: deploy/install_openvpn.yml
    - include: deploy/secure.yml    
