---
- hosts: baseinstall
  become: true
  vars:
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
    hostname: vpnbox-prod-bar.phu73l.net    
  tasks:
    - include: hostname_stage.yml  
