---
- name: load secrets
  include_vars: "install_openvpn_secrets.yml"
  no_log: true
- name: copy openvpn config
  copy:
    src: "{{ src }}/etc/openvpn/server/{{ item }}"
    dest: "/etc/openvpn/server/{{ item }}"
  with_items:
    - server.conf
#    - server-tcp.conf    
    - ca.crt
    - server.crt
    - server.key
    - dh.pem
    - ccd
- name: set ip forwarding in proc (and not the sysctl conf file?) and reload
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    # sysctl_set: yes
    reload: yes    
- name: enable and restart openvpn services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - openvpn-server@server
#    - openvpn-server@server-tcp
