---
# distro package setup and installation
- name: install selinux bindings, required since we start with selinux
  yum:
    name: libselinux-python
    state: present 
- name: remove yum packages
  yum:
    name:
      - audit
      - rpcbind
      - selinux-policy
      - selinux-policy-targeted
    state: absent
- name: update yum
  yum:
    name: "*"
    state: latest
- name: install epel-release yum package
  yum:
    name: epel-release
    state: present
- name: install yum packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - iptables-services
    - firewalld
    - ntp
    - man
    - vim-enhanced
    - openssh
    - openssh-server
    - openssh-clients
    - openssl-devel
    - cyrus-sasl-plain
    - openvpn
