---
# distro package setup and installation
- name: install selinux bindings, required since we start with selinux
  yum:
    name: python3-libselinux
    state: present 
- name: remove yum packages
  yum:
    name:
      - audit
      - rpcbind
      - selinux-policy
      - selinux-policy-targeted
      - sendmail
      - dracut-squash
    state: absent
- name: install epel yum package
  yum:
    name:
      - epel-release
- name: update yum
  yum:
    name: "*"
    state: latest
# should be replaced with "enablerepo: powertools" when installing packages?
- name: enable CentOS PowerTools repository for epel
  command: dnf config-manager --set-enabled powertools
- name: install yum packages
  yum:
    name:
      - chrony
      - cyrus-sasl-plain
      - dnsmasq
      - openssh
      - openssh-server
      - openssh-clients
      - openssl-devel
      - openvpn
      - postfix
      - rsync
    state: present
