---
- hosts: baseinstall
  become: true
  vars:
    src: "../src"
    local: "../local"    
    ansible_user: futel
    ansible_port: 42422
    ansible_ssh_private_key_file: conf/id_rsa
  tasks:
    - include: packages.yml
    - include: config.yml
    - include: install_openvpn.yml
    - include: install_dnsmasq.yml
    - include: update_iptables.yml