---
# firewall, port, ssh configuration
- name: write sshd config
  copy:
    src: src/etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
- name: restart sshd
  service:
    name: sshd
    state: restarted
- name: stop and enable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: yes
- name: stop and disable iptables
  service:
    name: iptables
    state: stopped
    enabled: no
- name: stop and disable ip6tables
  service:
    name: ip6tables
    state: stopped
    enabled: no



# XXX replace remove
- name: update iptables rules
  script: local/iptables.sh
- name: update ip6tables rules
  script: local/ip6tables.sh
- name: save iptables rules
  command: service iptables save
#  ignore_errors: yes # XXX this errors until a reboot?
- name: save ip6tables rules
  command: service ip6tables save
#  ignore_errors: yes # XXX this errors until a reboot?  
- name: start iptables
  service:
    name: iptables
    state: started
- name: start ip6tables
  service:
    name: ip6tables
    state: started
